name: flutter_social_login
description: Social login example for Flutter

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  fluro: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_facebook_auth: ^3.4.1
  flutter_naver_login: ^1.2.2
  fluttertoast: ^8.0.7
  get_it: ^7.1.3
  intl_utils: ^2.3.0
  kakao_flutter_sdk: ^0.6.3
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
